# Scientific computing in Python

## Arrays in Python

Arrays are a very useful and *fast* way of storing and manipulating like-type data. 

Their rapid computation is due to their ability to be initialized once at the beginning of a scipt and then referenced there-on out without needing to rewrite a new array to memory. Lists are slower because when a list is referenced and altered, the ENTIRE list has to be processed and written to memory. This effect does not matter all that much when dealing with small amounts of data. But if you have 1,000s or 10,000s of data points or are setting elements many times, arrays will save you significant time.

Arrays are not a part of the standard Python distribution, their functionality must instead be imported from separate libraries like `scipy` or `numpy`.

These arrays also include vectorization, meaning we can issue mathematica operations on the array as a whole rather than on individual elements. We'll show an example of this in a bit.

https://numpy.org/devdocs/user/absolute_beginners.html

In [6]:
# Let's import numpy. We only have to do this once in our notebook, 
# but if we reopen it or reset the kernal, make sure to run this cell again.
import numpy as np

In [7]:
# We can convert a standard Python list into a numpy array.
x_list = [0., 1., 2., 3., 4.]
a_arr = np.array(x_list)

print("a_arr:", a_arr)
print("Check the type of a_arr: ",type(a_arr))

# We can also initialize a numpy array as an array of zeros. 
# This reserves space in memory so we can access it quickly later.

b_arr = np.zeros(5)
print("\narray of zeros:", b_arr)

a_arr: [0. 1. 2. 3. 4.]
Check the type of a_arr:  <class 'numpy.ndarray'>

array of zeros: [0. 0. 0. 0. 0.]


In [9]:
# We can also create populated arrays in two ways.
# arange(start, end, step_size) does not include end value

c_arr = np.arange(0.0, 10.0, 1.0)
print(c_arr)

# linspace(start, end, number_of_elements) does include end value 
d_arr = np.linspace(0.0, 10.0, 10)
print(d_arr)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


## Array Manipulation: Slicing and Setting elements

In [10]:
# Can slice arrays similar to lists
x = d_arr[1:5]
print("array x, sliced from d_arr: ",x)

# Now, let's change the first element of this new array x
x[0] = 14.3
print("new array x:", x)

# But.. hold on a sec, let's check back in on d_arr
print("\nd_arr:", d_arr)

array x, sliced from d_arr:  [1.11111111 2.22222222 3.33333333 4.44444444]
new array x: [14.3         2.22222222  3.33333333  4.44444444]

d_arr: [ 0.         14.3         2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


### Array pointers vs. copies
So, even if we assign part of an array to a new variable, that new variable simply points back to the original array. Any changes we make to the pointer influences the source array.

If we want to instead create a separate array and make changes without affecting the original, we have to make a copy.

In [11]:
x = d_arr[6:10].copy()
print("array x, copied & sliced from d_arr: ",x)

# Now, let's change the first element of this new array x
x[-1] = 14.3333
print("new array x, replace 10.0 with 14.3:", x)

# And d_arr should be the same as in the previous cell.
print("\nd_arr:", d_arr)

array x, copied & sliced from d_arr:  [ 6.66666667  7.77777778  8.88888889 10.        ]
new array x, replace 10.0 with 14.3: [ 6.66666667  7.77777778  8.88888889 14.3333    ]

d_arr: [ 0.         14.3         2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


## Array Vectorization

No more need for looping over all elements to do some math!

y = np.array([12,22,37,43,51])

Given an array y, do the calculation:

$sin(y_{i})cos(y_{i}) e^{-y_{i}^2} + \frac{2}{y_{i}}$

Where $y_i$ represents each element of the array y.

In [ ]:
# If we tried to do this in the same way we did before, we would do somethign like this
y = np.array([12,22,37,43,51])
y_new = np.zeros(len(y))
for i, elem in enumerate(y):
    y_new[i] = np.sin(y[i]) * np.cos(y[i]) * np.exp(-y[i]**2) + 2/y[i]
    
print("y_new:", y_new)

# We can do this quicker and simpler now though!
y_new = np.sin(y) * np.cos(y) * np.exp(-y**2) + 2/y

print("\ny_new no looping:", y_new)

# Timing

Let's do another vectorization test, but this time let's see how much time we save via vectorization.

In [16]:
import time

start = time.perf_counter()
N=1000000
x = np.zeros(N); y = np.zeros(N)
dx = 2.0/(N-1) # spacing of x coordinates

for i in range(N):
    x[i] = -1 + dx*i
    y[i] = np.exp(-x[i])*x[i]
end = time.perf_counter()
time_elapsed = end-start
print("time elapsed:", time_elapsed)

print("-----Now Vectorize it-----")
start = time.perf_counter()
x=np.linspace(-1,1,N)
y=np.exp(-x)*x
end = time.perf_counter()
time_elapsed = end-start
print("time elapsed:", time_elapsed)

time elapsed: 2.8194904220001717
-----Now Vectorize it-----
time elapsed: 0.02124977499988745


There may not be a very big difference between the two methods in terms of timing (I've actually seen the "old way" operating faster from time to time). But try the above cell again and set N=10000.

On my machine, the vectorized method is 80x faster!!

Timing your work is really useful when building up scripts for your research (it also sounds really good when you can tell your research advisor that you improved your code's computation efficiency significantly).

Just to hammer things home, let's time the different functions for summing up the components of an array.

In [17]:
N = 100000
x=np.linspace(1,2,N)

# Built in way
start=time.perf_counter()
built_in=sum(x)
end=time.perf_counter()
elapsed=end-start
print("sum(x)=%d, calculated in %f seconds"%(built_in, elapsed))

# numpy way
start=time.perf_counter()
numpy_way=np.sum(x)
end=time.perf_counter()
elapsed=end-start
print("np.sum(x)=%d, calculated in %f seconds"%(built_in, elapsed))

# array way
start=time.perf_counter()
numpy_way=x.sum()
end=time.perf_counter()
elapsed=end-start
print("x.sum()=%d, calculated in %f seconds"%(built_in, elapsed))

sum(x)=150000, calculated in 0.035919 seconds
np.sum(x)=150000, calculated in 0.000486 seconds
x.sum()=150000, calculated in 0.000283 seconds


There are other array unitary functions that you should try to use whenever possible to save time!

    .sum()
    .max()
    .min
    .prod()
    .trace()
    .round()
    .var()
    .conj()
    .mean()
    .std()
    
Arrays can also be treated as vectors and vector operations can be used:
   
    numpy.dot(vec1, vec2)
    numpy.cross(vec1, vec2)
    
And can also perform boolean comparisons.

See here for a full summary: http://docs.scipy.org/doc/numpy/reference/routines.logic.html


# Practicals! Do 1-3

1. Create and array of cos(x) and a second array of sin(x) spaced in increments of 0.1. Using these, create a third array  of $cos(x)^2 + sin(x)^2$


2. Write a function that computes: $f(x) = x^3 +xe^x +1$ and apply this function to each element in an array.


3. Write a function that takes in two vectors and prints whether they are parallel, perpendicular, or neither.

In [34]:
# 1. 
from math import pi,cos,sin

x = np.arange(0.0,2*pi, 0.1)
b = x.copy
#c = x.copy
#print(sin_array)

print(b)
#x = np.sin(x)

#print(x)

#b = np.cos(b)
#print(b)




<built-in method copy of numpy.ndarray object at 0x114272f80>


In [35]:
# 2.

def f(x):
    ans = x**3 + x*exp(x)+1
    return(ans)



In [ ]:
# 3.

from import 
def vector(vector1,vector2):
    if (np.dot(vector1,vector2)/np.abs(np.dot(vector1,vector2))) == 1:
        
    



# Higher Dimensional Arrays

Numpy can handle and manipulate 2 and 3D arrays.

In [ ]:
# We can make a 3 dimensional array of 1's. Imagine a 3x3x3 cube. 
# When we print this matrix, we see each slice of the cube.
x3D = np.ones((3,3,3))
print(x3D)

In [ ]:
# Make a 2d array
twoD_Array = np.array([[3,4],[5,7]])

print("2D array:\n", twoD_Array)
print("Transpose:\n", twoD_Array.T)

reshaped_arr = np.reshape(twoD_Array,(1,4))
print("1x4 array:\n", reshaped_arr)

Numpy matrices can be created via numpy array routines as we saw above, and with functions like `numpy.zeros()` `numpy.ones()`, `numpy.ones_like()`

And different sections of the matrix can be accessed via `numpy.diag()`, `numpy.tril()`, `numpy.triu()`

And the matrix object can be compressed back into a 1D array with `[mat_obj].flatten()`

# Linear Algebra

* Linear algebra python packages
    * scipy.linalg
    * numpy.linalg
* Eigenvectors/eigenvalues found with eig command
    * eval, eVec = linalg.eig(A)

# Practicals! Do 4-6

4. Create an array between 0 and 100 with N$*$M steps. Convert this into an NxM matrix

5. Write a function that takes a 1x2 array and an angle. Multiply the array by the rotation matrix R and return the rotated array: $R = \begin{bmatrix} cos\theta & -sin\theta \\ sin\theta & cos\theta \end{bmatrix}$

6. Create a matrix and show that U_inverse$*$A$*$U = diagonal matrix
    * U is matrix of eigenvectors
    * print eigenvalues and compare to your answer

In [45]:
# 4.

import numpy as np

N =20
M =5
total = N*M
dx = 100/total

counting = np.zeros((N,M))

for i in range (0,N):
    for l in range (0,M):
        counting[i][l]= counting[i][l-1]+dx
    
print(counting)


[[1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]]


In [ ]:
# 5.



In [ ]:
# 6.



# Random Numbers

Generating random numbers is a science in itself when it comes to computation. Generally, there are two methods that are the most useful for us: `numpy.random` and `scipy.random`

The `random` function in the `numpy.random` class which returns a list of random numbers in the range 0,1

There are also other functions that produce random numbers in a specified distribution (e.g. poisson, uniform, triangular, etc.)


http://docs.scipy.org/doc/numpy/reference/routines.random.html

In [ ]:
print(np.random.random(10))

# Other Routines

There's also other routines in `scipy` that can be very useful.
* Integration
    * `scipy.integrate` module
* Fourier Transform
    * Module `scypi` (or `numpy`)`.fft`
* Curve Fitting
    * `scipy.optimize.curve_fit()`